{% set name = "bertopic" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bertopic-{{ version }}.tar.gz
  sha256: bc5e68d21a9882cb3d2f7adac231e2d16431e6fa1e927b0efed33a4648c2b988

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    # This is a temporary workaround; review in the future
    - pyyaml <6.0
    - umap-learn >=0.5.0
    - hdbscan >=0.8.27
    - numpy >=1.20.0
    - pandas >=1.1.5
    - plotly >=4.7.0
    - scikit-learn >=0.22.2.post1
    - sentence-transformers >=0.4.1
    - tqdm >=4.41.1
    - cython
    - pyarrow >=6.0.0

test:
  imports:
    - bertopic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MaartenGr/BERTopic
  summary: BERTopic performs topic Modeling with state-of-the-art transformer models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mimshiran
    - MaartenGr
