schema_version: 1

context:
  name: bertopic
  version: "0.17.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/bertopic-${{ version }}.tar.gz
  sha256: 3f876d2eadf2037df79f059b734935d7ed2eb6f530bcc6c7a19e1a8f5d2cbaba

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - hdbscan >=0.8.29
    - numpy >=1.20.0
    - pandas >=1.1.5
    - plotly >=4.7.0
    - scikit-learn >=1.0
    - sentence-transformers >=0.4.1
    - tqdm >=4.41.1
    - umap-learn >=0.5.0

tests:
  - python:
      imports:
        - bertopic
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/MaartenGr/BERTopic
  summary: BERTopic performs topic Modeling with state-of-the-art transformer models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - mimshiran
    - MaartenGr
